name: Xiaowei (Elliott) Zhang
title: Welcome to my homepage
description: My name is : Xiaowei (Elliott) Zhang. I’m currently a Ph.D. candidate of Information Systems in Department of Management Science and Engineering, Tsinghua University.
tags:
  - Digital Platforms: Sharing Economy, E-commerce Platforms, Platform Governance
  - Artificial Intelligence
show_hero: true
menu:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Research
    url: /research
  - title: Talks
    url: /talks
  - title: Contact
    url: /contact
email: xw-zhang21@mails.tsinghua.edu.cn
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
